version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/phoenix_chat_demo
    links:
      - db
    environment:
      - POSTGRES_HOST=db
  db:
    image: "postgres:9.6.3"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
